ELIoT
EricssonResearch/scott-eu pull request #56
Opened 2017-10-31 08:09 UTC by bluelancer

A simulation of LWM2M communication between Digital twins and LWM2M server, In both source code and docker image.

Reference: https://github.com/Alliasd/ELIoT/wiki/Emulated-IoT-(ELIoT)-Platform

2017-11-24 12:34 UTC, berezovskyi requested changes

2017-11-24 12:34 UTC, berezovskyi commented on .gitignore
> +ELIoT/CoapNode/src/app/node_modules/
would be best to have a separate `.gitignore` file in `ELIoT/CoapNode/`

2017-11-24 12:34 UTC, berezovskyi commented on ELIoT/CoapNode/src/.idea/modules.xml
> +<?xml version="1.0" encoding="UTF-8"?>
I think IntelliJ folder should not be there.

2017-11-24 12:34 UTC, berezovskyi commented on ELIoT/demo/ELIoT/devices/out/Refresh_coordinate.html
> +<!DOCTYPE html>
Shall the `/out/` folder be ignored?

2017-11-24 12:34 UTC, berezovskyi commented on ELIoT/demo/ELIoT/jsdoc-toolkit/app/frame/Dumper.js
> +/**
Do we need to share the `jsdoc-toolkit` code here as well?

2017-11-24 12:34 UTC, berezovskyi commented on ELIoT/leshan/leshan.iml
> +<?xml version="1.0" encoding="UTF-8"?>
We need to remove IntelliJ and JAR files from here.

2017-11-24 12:34 UTC, berezovskyi commented on mqtt/README.md
> +Purpose: MQTT broker
What is this?

2017-11-24 15:41 UTC, bluelancer commented
@berezovskyi maybe better now?

2018-01-20 15:28 UTC, berezovskyi approved these changes

2018-01-20 15:28 UTC, merged